/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manajemeninventaris.view;

import manajemeninventaris.auth.LoginRegister;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import manajemeninventaris.Role;
import manajemeninventaris.Session;

/**
 *
 * @author Acer
 */
public class MainJFrame extends javax.swing.JFrame {
    //Pendeklarasian CardLayout untuk Fragmentasi
    private final CardLayout cardLayout = new CardLayout();
    
    //pendeklarasian warna
    protected final Color warnaAbu = new Color(138, 138, 138);
    protected final Color warnaHitam = new Color(37, 37, 37);
    protected final Color warnaPAbu = new Color(229, 225, 226);
    
    //Pendeklarasian Button Events untuk Aktif/Nonaktif mouseEvents
    private boolean btnDashboardEvents = true;
    private boolean btnBarangEvents = true;
    private boolean btnTransaksiEvents = true;
    private boolean btnPenggunaEvents = true;
    private boolean btnLaporanEvents = true;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        GambarProfile();
        layoutFragment();
        dataSesi();
        roleButton();
        
        //Membuat FullScreen
        setExtendedState(MainJFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(MainJFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Form = new javax.swing.JPanel();
        NavBar = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnPengguna = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JButton();
        HeadBar = new javax.swing.JPanel();
        lbGreeting = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Profile = new javax.swing.JLabel();
        lbNamaUser = new javax.swing.JLabel();
        lbRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manajemen Inventaris");
        setMinimumSize(new java.awt.Dimension(1366, 600));

        Form.setMaximumSize(new java.awt.Dimension(1114, 658));
        Form.setPreferredSize(new java.awt.Dimension(1114, 485));
        Form.setLayout(new java.awt.CardLayout());

        NavBar.setBackground(new java.awt.Color(37, 37, 37));
        NavBar.setPreferredSize(new java.awt.Dimension(246, 621));

        btnDashboard.setBackground(new java.awt.Color(37, 37, 37));
        btnDashboard.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnDashboard.setForeground(warnaAbu);
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setPreferredSize(new java.awt.Dimension(246, 45));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
        });
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(37, 37, 37));
        btnBarang.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBarang.setForeground(warnaAbu);
        btnBarang.setText("Barang");
        btnBarang.setBorder(null);
        btnBarang.setFocusPainted(false);
        btnBarang.setPreferredSize(new java.awt.Dimension(246, 45));
        btnBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBarangMouseExited(evt);
            }
        });
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(37, 37, 37));
        btnTransaksi.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnTransaksi.setForeground(warnaAbu);
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setBorder(null);
        btnTransaksi.setFocusPainted(false);
        btnTransaksi.setPreferredSize(new java.awt.Dimension(246, 45));
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnPengguna.setBackground(new java.awt.Color(37, 37, 37));
        btnPengguna.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnPengguna.setForeground(warnaAbu);
        btnPengguna.setText("Pengguna");
        btnPengguna.setBorder(null);
        btnPengguna.setFocusPainted(false);
        btnPengguna.setPreferredSize(new java.awt.Dimension(246, 45));
        btnPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPenggunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPenggunaMouseExited(evt);
            }
        });
        btnPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenggunaActionPerformed(evt);
            }
        });

        btnLogout.setText("Log Out");
        btnLogout.setBorder(null);
        btnLogout.setFocusPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistem Manajemen");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inventaris");

        btnLaporan.setBackground(new java.awt.Color(37, 37, 37));
        btnLaporan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnLaporan.setForeground(warnaAbu);
        btnLaporan.setText("Laporan");
        btnLaporan.setBorder(null);
        btnLaporan.setFocusPainted(false);
        btnLaporan.setPreferredSize(new java.awt.Dimension(246, 45));
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanMouseExited(evt);
            }
        });
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73))))
            .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        HeadBar.setBackground(new java.awt.Color(73, 54, 40));
        HeadBar.setPreferredSize(new java.awt.Dimension(1114, 136));

        lbGreeting.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbGreeting.setForeground(new java.awt.Color(255, 255, 255));
        lbGreeting.setText("Halo, Selamat Datang Atmin");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mau ubah data apa hari ini?");

        Profile.setText("jLabel5");

        lbNamaUser.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        lbNamaUser.setText("Adam Yudistira");

        lbRole.setForeground(new java.awt.Color(255, 255, 255));
        lbRole.setText("Atmin");

        javax.swing.GroupLayout HeadBarLayout = new javax.swing.GroupLayout(HeadBar);
        HeadBar.setLayout(HeadBarLayout);
        HeadBarLayout.setHorizontalGroup(
            HeadBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadBarLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(HeadBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lbGreeting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HeadBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNamaUser)
                    .addComponent(lbRole))
                .addGap(18, 18, 18)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        HeadBarLayout.setVerticalGroup(
            HeadBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadBarLayout.createSequentialGroup()
                .addGroup(HeadBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeadBarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(HeadBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HeadBarLayout.createSequentialGroup()
                                .addComponent(lbGreeting)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))))
                    .addGroup(HeadBarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbNamaUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbRole)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeadBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeadBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Form, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Menyesuaikan Button Sesuai Role
    private void roleButton() {
        Session session = Session.getInstance();
        switch(session.getRole()){
            case "Pengelola Barang" -> Role.setNotVisible("Pengelola Barang", btnPengguna, btnLaporan);
            case "Supervisor" -> Role.setNotVisible("Supervisor", btnPengguna);
            case "Karyawan" -> Role.setNotVisible("Karyawan", btnBarang, btnTransaksi, btnPengguna);
            default -> {
            }
        }
    }
    
    //Method untuk pendeklarasian panel yang merupakan fragmentasi
    private void layoutFragment(){
        Form.setLayout(cardLayout);
        Form.add(new pnl_dashboard(), "dashboard");
        Form.add(new pnl_dtbarangnew(), "dtbarang");
        Form.add(new pnl_dttransaksi(), "dttransaksi");
        Form.add(new pnl_pengguna(), "dtpengguna");
        Form.add(new pnl_dtlaporan(), "dtlaporan");
    }
    
    //Method untuk mengubah Tampilan sesuai Sesi
    private void dataSesi() {
        Session session = Session.getInstance();
        lbGreeting.setText("Halo, Selamat Datang " + session.getUsername());
        lbNamaUser.setText(session.getUsername());
        lbRole.setText(session.getRole());
    }
    
    //Menampilkan Gambar poto profile
    private void GambarProfile() {
    ImageIcon icon = new ImageIcon(MainJFrame.class.getResource("/image/Profile WA Amba.jpeg"));
    Image img = icon.getImage();
    Image scaledImg = img.getScaledInstance(Profile.getWidth(), Profile.getHeight(), Image.SCALE_SMOOTH);
    Profile.setIcon(new ImageIcon(scaledImg));
}

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        if(btnDashboardEvents){
            btnDashboard.setBackground(warnaAbu);
            btnDashboard.setForeground(warnaHitam);
        }
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseEntered
        // TODO add your handling code here:
        if(btnBarangEvents){
            btnBarang.setBackground(warnaAbu);
            btnBarang.setForeground(warnaHitam);
        }
    }//GEN-LAST:event_btnBarangMouseEntered

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        // TODO add your handling code here:
        if(btnTransaksiEvents){
            btnTransaksi.setBackground(warnaAbu);
            btnTransaksi.setForeground(warnaHitam);
        }
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnPenggunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenggunaMouseEntered
        // TODO add your handling code here:
        if(btnPenggunaEvents){
            btnPengguna.setBackground(warnaAbu);
            btnPengguna.setForeground(warnaHitam);
        }
    }//GEN-LAST:event_btnPenggunaMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        // TODO add your handling code here:
        if(btnDashboardEvents){
            btnDashboard.setBackground(warnaHitam);
            btnDashboard.setForeground(warnaAbu);
        }
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseExited
        // TODO add your handling code here:
        if(btnBarangEvents){
            btnBarang.setBackground(warnaHitam);
            btnBarang.setForeground(warnaAbu);
        }
    }//GEN-LAST:event_btnBarangMouseExited

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        // TODO add your handling code here:
        if(btnTransaksiEvents){
            btnTransaksi.setBackground(warnaHitam);
            btnTransaksi.setForeground(warnaAbu);
        }
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnPenggunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenggunaMouseExited
        // TODO add your handling code here:
        if(btnPenggunaEvents){
            btnPengguna.setBackground(warnaHitam);
            btnPengguna.setForeground(warnaAbu);
        }
    }//GEN-LAST:event_btnPenggunaMouseExited

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        btnDashboardEvents = false;
        btnBarangEvents = true;
        btnTransaksiEvents = true;
        btnPenggunaEvents = true;  
        btnLaporanEvents = true;
        
        btnDashboard.setBackground(warnaPAbu);
        btnBarang.setBackground(warnaHitam);
        btnTransaksi.setBackground(warnaHitam);
        btnPengguna.setBackground(warnaHitam);  
        btnLaporan.setBackground(warnaHitam);
        
        btnDashboard.setForeground(warnaHitam);
        btnBarang.setForeground(warnaAbu);
        btnTransaksi.setForeground(warnaAbu);
        btnPengguna.setForeground(warnaAbu); 
        btnLaporan.setForeground(warnaAbu); 
        
        cardLayout.show(Form, "dashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        btnDashboardEvents = true;
        btnBarangEvents = false;
        btnTransaksiEvents = true;
        btnPenggunaEvents = true; 
        btnLaporanEvents = true;
        
        btnDashboard.setBackground(warnaHitam);
        btnBarang.setBackground(warnaPAbu);
        btnTransaksi.setBackground(warnaHitam);
        btnPengguna.setBackground(warnaHitam);
        btnLaporan.setBackground(warnaHitam);
        
        btnDashboard.setForeground(warnaAbu);
        btnBarang.setForeground(warnaHitam);
        btnTransaksi.setForeground(warnaAbu);
        btnPengguna.setForeground(warnaAbu);
        btnLaporan.setForeground(warnaAbu); 
            
        cardLayout.show(Form, "dtbarang");
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        btnDashboardEvents = true;
        btnBarangEvents = true;
        btnTransaksiEvents = false;
        btnPenggunaEvents = true;   
        btnLaporanEvents = true;
        
        btnDashboard.setBackground(warnaHitam);
        btnBarang.setBackground(warnaHitam);
        btnTransaksi.setBackground(warnaPAbu);
        btnPengguna.setBackground(warnaHitam);
        btnLaporan.setBackground(warnaHitam);
        
        btnDashboard.setForeground(warnaAbu);
        btnBarang.setForeground(warnaAbu);
        btnTransaksi.setForeground(warnaHitam);
        btnPengguna.setForeground(warnaAbu); 
        btnLaporan.setForeground(warnaAbu); 
              
        cardLayout.show(Form, "dttransaksi");
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenggunaActionPerformed
        btnDashboardEvents = true;
        btnBarangEvents = true;
        btnTransaksiEvents = true;
        btnPenggunaEvents = false;  
        btnLaporanEvents = true;
        
        btnDashboard.setBackground(warnaHitam);
        btnBarang.setBackground(warnaHitam);
        btnTransaksi.setBackground(warnaHitam);
        btnPengguna.setBackground(warnaPAbu);
        btnLaporan.setBackground(warnaHitam);
        
        btnDashboard.setForeground(warnaAbu);
        btnBarang.setForeground(warnaAbu);
        btnTransaksi.setForeground(warnaAbu);
        btnPengguna.setForeground(warnaHitam); 
        btnLaporan.setForeground(warnaAbu); 
         
        cardLayout.show(Form, "dtpengguna");
    }//GEN-LAST:event_btnPenggunaActionPerformed

    //Tombol untuk Log Out
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        JFrame form = new LoginRegister();
        form.setVisible(true);
        
        Session session = Session.getInstance();
        session.clear();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseEntered
        if(btnLaporanEvents){
            btnLaporan.setBackground(warnaAbu);
            btnLaporan.setForeground(warnaHitam);
        }
    }//GEN-LAST:event_btnLaporanMouseEntered

    private void btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseExited
        if(btnLaporanEvents){
            btnLaporan.setBackground(warnaHitam);
            btnLaporan.setForeground(warnaAbu);
        }
    }//GEN-LAST:event_btnLaporanMouseExited

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        btnDashboardEvents = true;
        btnBarangEvents = true;
        btnTransaksiEvents = true;
        btnPenggunaEvents = true;
        btnLaporanEvents = false;
        
        btnDashboard.setBackground(warnaHitam);
        btnBarang.setBackground(warnaHitam);
        btnTransaksi.setBackground(warnaHitam);
        btnPengguna.setBackground(warnaHitam);
        btnLaporan.setBackground(warnaPAbu);
        
        btnDashboard.setForeground(warnaAbu);
        btnBarang.setForeground(warnaAbu);
        btnTransaksi.setForeground(warnaAbu);
        btnPengguna.setForeground(warnaAbu); 
        btnLaporan.setForeground(warnaHitam); 
        
        cardLayout.show(Form, "dtlaporan");
    }//GEN-LAST:event_btnLaporanActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Form;
    private javax.swing.JPanel HeadBar;
    private javax.swing.JPanel NavBar;
    private javax.swing.JLabel Profile;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPengguna;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbGreeting;
    private javax.swing.JLabel lbNamaUser;
    private javax.swing.JLabel lbRole;
    // End of variables declaration//GEN-END:variables
}
