/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manajemeninventaris.view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Acer
 */
public class pnl_dashboard extends javax.swing.JPanel {

    /**
     * Creates new form pnl_dashboard
     */
    public pnl_dashboard() {
        initComponents();
        GambarDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDashboard = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 465));

        lbDashboard.setMinimumSize(new java.awt.Dimension(1144, 420));
        lbDashboard.setPreferredSize(new java.awt.Dimension(1100, 465));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //Menampilkan Gambar pada Dashboard
    private void GambarDashboard() {
        ImageIcon icon = new ImageIcon(pnl_dashboard.class.getResource("/image/Dashboard.jpg"));
        Image img = icon.getImage();
        Image scaledImg = img.getScaledInstance(1108, 540, Image.SCALE_SMOOTH);
        lbDashboard.setIcon(new ImageIcon(scaledImg));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbDashboard;
    // End of variables declaration//GEN-END:variables
}
