/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manajemeninventaris.view;

import javax.swing.*;
import manajemeninventaris.Role;
import manajemeninventaris.Session;
import manajemeninventaris.controller.LaporanController;
import manajemeninventaris.model.Laporan;

/**
 *
 * @author Acer
 */
public class pnl_dtlaporan extends javax.swing.JPanel {
    /**
     * Creates new form pnl_dtlaporan()
     */
    public pnl_dtlaporan() {
        initComponents();
        roleButton();
        
        read();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdLaporan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCatatan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbTipe = new javax.swing.JComboBox<>();
        dateTAwal = new com.toedter.calendar.JDateChooser();
        dateTAkhir = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        scrDaftarLaporan = new javax.swing.JScrollPane();
        pnlDaftarLaporan = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1114, 420));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1034, 420, -1, -1));

        jPanel1.setBackground(new java.awt.Color(214, 192, 179));
        jPanel1.setPreferredSize(new java.awt.Dimension(526, 330));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ID Laporan   ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 48, 108, 26));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tanggal Awal         ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 125, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tanggal Akhir ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 168, 151, 26));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Catatan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 212, 151, 26));

        txtIdLaporan.setPreferredSize(new java.awt.Dimension(105, 22));
        txtIdLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLaporanActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 53, 235, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tipe");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 87, 151, 26));
        jPanel1.add(txtCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 217, 235, -1));

        btnTambah.setBackground(new java.awt.Color(73, 54, 40));
        btnTambah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 269, -1, -1));

        jButton4.setBackground(new java.awt.Color(73, 54, 40));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 269, -1, -1));

        cbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barang", "Transaksi", "Pengguna" }));
        cbTipe.setSelectedIndex(-1);
        jPanel1.add(cbTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 87, 235, 26));
        jPanel1.add(dateTAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 128, 235, -1));
        jPanel1.add(dateTAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 172, 235, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 58, -1, 340));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("Form Laporan");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 17, 197, 35));

        pnlDaftarLaporan.setLayout(new javax.swing.BoxLayout(pnlDaftarLaporan, javax.swing.BoxLayout.Y_AXIS));
        scrDaftarLaporan.setViewportView(pnlDaftarLaporan);

        add(scrDaftarLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 58, 531, 340));
    }// </editor-fold>//GEN-END:initComponents
    
    //Fungsi untuk disable Button sesuai role
    private void roleButton() {
        Session session = Session.getInstance();
        switch(session.getRole()){
            case "Supervisor" -> Role.setNoAccessButton("Supervisor", btnTambah);
            default -> {
            }
        }
    }
    
    //Menampilkan Data Laporan ke panel
    public void read(){
        try {
            new LaporanController().index(pnlDaftarLaporan);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal : " + e.getMessage(), "Gagal menampilkan Data Laporan", JOptionPane.ERROR_MESSAGE);
        }   
    }
    
    //Fungsi mengosongkan Komponen Form
    private void kosong(){
        txtIdLaporan.setText(null);
        cbTipe.setSelectedItem(null);
        dateTAwal.setDate(null);
        dateTAkhir.setDate(null);
        txtCatatan.setText(null);
    }
    
    private void txtIdLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLaporanActionPerformed

    //Menambah Data Laporan Baru
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        //Mengambil data dari komponen
        String id = txtIdLaporan.getText();
        String tipe = cbTipe.getSelectedItem().toString();
        String TAwal = dateTAwal.getDate().toString();
        String TAkhir = dateTAkhir.getDate().toString();
        String catatan = txtCatatan.getText();
        String IDUser = Session.getInstance().getID();
        String file = "ambafile";
        
        try {
            //Menambah data ke database
            Laporan laporan = new Laporan();
            laporan.setId(id);
            laporan.setTipe(tipe);
            laporan.setCatatan(catatan);
            laporan.setIdUser(IDUser);
            laporan.setFile(file);
            new LaporanController().store(laporan);
            
            //Pesan jika berhasil
            JOptionPane.showMessageDialog(null, "Berhasil menambahkan Data Laporan");
        } catch (Exception e) {
            //Pesan jika gagal
            JOptionPane.showMessageDialog(null, "Gagal : " + e.getMessage(), "Gagal menambahkan Data Laporan", JOptionPane.ERROR_MESSAGE);
        }

        read();
        kosong();
    }//GEN-LAST:event_btnTambahActionPerformed

    //Mengosongkan Komponen Form
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        read();
        kosong();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbTipe;
    private com.toedter.calendar.JDateChooser dateTAkhir;
    private com.toedter.calendar.JDateChooser dateTAwal;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlDaftarLaporan;
    private javax.swing.JScrollPane scrDaftarLaporan;
    private javax.swing.JTextField txtCatatan;
    private javax.swing.JTextField txtIdLaporan;
    // End of variables declaration//GEN-END:variables
}
