/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manajemeninventaris.view;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import manajemeninventaris.Role;
import manajemeninventaris.Session;
import manajemeninventaris.config;
import manajemeninventaris.controller.TransaksiController;
import manajemeninventaris.model.Transaksi;

/**
 *
 * @author Acer
 */
public class pnl_dttransaksi extends javax.swing.JPanel {
    
    /**
     * Creates new form pnl_dtbarang
     */
    public pnl_dttransaksi() {
        initComponents();
        roleButton();
        
        read();
        isicbidbrg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtidtrans = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtjml = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbtipe = new javax.swing.JComboBox<>();
        cbidbrg = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(1114, 658));
        setPreferredSize(new java.awt.Dimension(1114, 420));

        tblData.setAutoCreateRowSorter(true);
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblData.setPreferredSize(new java.awt.Dimension(557, 330));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setText("Form Transaksi");

        jPanel1.setBackground(new java.awt.Color(214, 192, 179));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 260));
        jPanel1.setPreferredSize(new java.awt.Dimension(526, 330));

        btnTambah.setBackground(new java.awt.Color(73, 54, 40));
        btnTambah.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(73, 54, 40));
        btnEdit.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(73, 54, 40));
        btnHapus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(73, 54, 40));
        btnBatal.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ID Transaksi");
        jLabel1.setMaximumSize(new java.awt.Dimension(106, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(106, 16));

        txtidtrans.setMinimumSize(new java.awt.Dimension(105, 22));
        txtidtrans.setPreferredSize(new java.awt.Dimension(105, 22));
        txtidtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidtransActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ID Barang");
        jLabel2.setMaximumSize(new java.awt.Dimension(106, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(106, 16));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("jumlah");
        jLabel5.setMaximumSize(new java.awt.Dimension(106, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(106, 16));

        txtjml.setPreferredSize(new java.awt.Dimension(105, 22));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tipe");
        jLabel4.setMaximumSize(new java.awt.Dimension(106, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(106, 16));

        cbtipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penambahan", "Pengurangan" }));
        cbtipe.setSelectedIndex(-1);
        cbtipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipeActionPerformed(evt);
            }
        });

        cbidbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbidbrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(txtidtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(cbtipe, 0, 319, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(txtjml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(cbidbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnTambah)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addComponent(btnBatal)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbidbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbtipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnBatal)
                    .addComponent(btnHapus))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Menyesuaikan Button Sesuai Role
    private void roleButton() {
        Session session = Session.getInstance();
        switch(session.getRole()){
            case "Supervisor" -> Role.setNoAccessButton("Supervisor", btnTambah, btnEdit, btnHapus);
            default -> {
            }
        }
    }
    
    //Menambah Data Transaksi Baru
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        //Mengambil data dari komponen
        String id = txtidtrans.getText();
        String idBrg = cbidbrg.getSelectedItem().toString();
        String idUser = Session.getInstance().getID();
        String tipe = cbtipe.getSelectedItem().toString();
        int jumlah = Integer.parseInt(txtjml.getText());
              
        try {
            //Menambah data ke database
            Transaksi transaksi = new Transaksi();
            transaksi.setId(id);
            transaksi.setIdBarang(idBrg);
            transaksi.setIdUser(idUser);
            transaksi.setTipe(tipe);
            transaksi.setJumlah(jumlah);
            new TransaksiController().store(transaksi);
            
            //Pesan jika berhasil
            JOptionPane.showMessageDialog(null, "Berhasil menambahkan Data Transaksi");
        } catch(Exception e) {
            //Pesan jika gagal
            JOptionPane.showMessageDialog(null, "Gagal : " + e.getMessage(), "Gagal menambahkan Data Transaksi", JOptionPane.ERROR_MESSAGE);
        }
        read();
        kosong();
    }//GEN-LAST:event_btnTambahActionPerformed

    //Menampilkan data dari database ke tabel
    private void read() {
        try {
            new TransaksiController().index(tblData);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal : " + e.getMessage(), "Gagal menampilkan Transaksi", JOptionPane.ERROR_MESSAGE);
        }   
    }
   
    //Fungsi mengosongkan Komponen Form
    private void kosong(){
        txtidtrans.setText(null);
        cbidbrg.setSelectedItem(null);
        txtjml.setText(null);  
        cbtipe.setSelectedItem(null);
    }
      
    private void cbtipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipeActionPerformed

    //Mengedit Data Transaksi
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        //Mengambil data dari komponen
        String id = txtidtrans.getText();
        String idBrg = cbidbrg.getSelectedItem().toString();
        String idUser = Session.getInstance().getID();
        String tipe = cbtipe.getSelectedItem().toString();
        int jumlah = Integer.parseInt(txtjml.getText());
              
        try {
            //Menambah data ke database
            Transaksi transaksi = new Transaksi();
            transaksi.setId(id);
            transaksi.setIdBarang(idBrg);
            transaksi.setIdUser(idUser);
            transaksi.setTipe(tipe);
            transaksi.setJumlah(jumlah);
            new TransaksiController().update(transaksi);
            
            //Pesan jika berhasil
            JOptionPane.showMessageDialog(null, "Berhasil mengubah Data Transaksi");
        } catch(Exception e) {
            //Pesan jika gagal
            JOptionPane.showMessageDialog(null, "Gagal : " + e.getMessage(), "Gagal mengubah Data Transaksi", JOptionPane.ERROR_MESSAGE);
        }
        read();
        kosong();
    }//GEN-LAST:event_btnEditActionPerformed
    
    // Menampilkan Data ke Komponen Form
    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.rowAtPoint(evt.getPoint());
        String idtrans =tblData.getValueAt(baris, 1).toString();
        txtidtrans.setText(idtrans);
        
        String idbrg = tblData.getValueAt(baris,2).toString();
        cbidbrg.setSelectedItem(idbrg);
        
        String tipe =tblData.getValueAt(baris, 4).toString();
        cbtipe.setSelectedItem(tipe);
        
        String jml = tblData.getValueAt(baris, 5).toString();
        txtjml.setText(jml);
    }//GEN-LAST:event_tblDataMouseClicked

    // Mengosongkan Komponen Form
    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        read();
        kosong();
    }//GEN-LAST:event_btnBatalActionPerformed

    // Menghapus Data Transaksi
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String id = txtidtrans.getText();
              
        try {
            //menghapus data dari database
            new TransaksiController().destroy(id);
            
            //Pesan jika berhasil
            JOptionPane.showMessageDialog(null, "Berhasil menghapus Data Transaksi");
        } catch(Exception e) {
            //Pesan jika gagal
            JOptionPane.showMessageDialog(null, "Gagal : " + e.getMessage(), "Gagal menghapus Data Transaksi", JOptionPane.ERROR_MESSAGE);
        }
        read();
        kosong();
    }//GEN-LAST:event_btnHapusActionPerformed

    // Mengisi Comobo Box ID Barang berdasarkan ID pada Tabel Barang
    private void isicbidbrg() {        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        
        try{
            String sql = "select Id_barang from barang";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {
                model.addElement(res.getString("Id_barang"));
            }
        } catch (Exception e) { 
        }
  
        cbidbrg.setModel(model);
        cbidbrg.setSelectedItem(null);
    }
    
    private void cbidbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbidbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbidbrgActionPerformed

    private void txtidtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidtransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidtransActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbidbrg;
    private javax.swing.JComboBox<String> cbtipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtidtrans;
    private javax.swing.JTextField txtjml;
    // End of variables declaration//GEN-END:variables
}
