/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manajemeninventaris.auth;

import java.sql.*;
import javax.swing.*;
import java.time.LocalDate;
import manajemeninventaris.view.MainJFrame;
import manajemeninventaris.Session;
import manajemeninventaris.config;
import manajemeninventaris.model.User;
import manajemeninventaris.controller.UserController;

/**
 *
 * @author Acer
 */
public class pnl_register extends javax.swing.JPanel {
    private LoginRegister form;
    /**
     * Creates new form pnl_login
     */
    public pnl_register(LoginRegister frame) {
        this.form = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        btnMasuk = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        txtKonfirmasiPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(400, 373));
        setPreferredSize(new java.awt.Dimension(400, 372));

        txtUsername.setBackground(new java.awt.Color(254, 254, 254));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setForeground(form.warnaAbu);
        txtUsername.setText("Username");
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnMasuk.setBackground(new java.awt.Color(254, 254, 254));
        btnMasuk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMasuk.setText("Masuk");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(254, 254, 254));
        txtPassword.setForeground(form.warnaAbu);
        txtPassword.setText("Password");
        txtPassword.setEchoChar((char) 0);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setText("Register Form");

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnLogin.setBackground(new java.awt.Color(254, 254, 254));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setText("Log In");
        btnLogin.setFocusPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin);

        btnRegister.setBackground(new java.awt.Color(73, 54, 40));
        btnRegister.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.setFocusPainted(false);
        jPanel3.add(btnRegister);

        txtKonfirmasiPassword.setBackground(new java.awt.Color(254, 254, 254));
        txtKonfirmasiPassword.setForeground(form.warnaAbu);
        txtKonfirmasiPassword.setText("Konfirmasi Password");
        txtKonfirmasiPassword.setEchoChar((char) 0);
        txtKonfirmasiPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKonfirmasiPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKonfirmasiPasswordFocusLost(evt);
            }
        });
        txtKonfirmasiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKonfirmasiPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMasuk)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)
                            .addComponent(txtKonfirmasiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtKonfirmasiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMasuk)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(237, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    //Tombol untuk Register beserta Fungsi Register
    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        String iduser = idbaru();
        String username = txtUsername.getText();
        String password;
        String role = "Karyawan";
        
        //Cek bahwa Password dan Konfirmasi Password sama
        if(!txtPassword.getText().equals(txtKonfirmasiPassword.getText())){
            JOptionPane.showMessageDialog(this, "Harap Periksa Password Kembali", "Error 2", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            password = PasswordUtils.hashPassword(txtPassword.getText());
        }
        
        //Memasukkan Data User Baru
        try{
            User user = new User();
            user.setId(iduser);
            user.setUsername(username);
            user.setPassword(password);
            user.setRole(role);
            new UserController().store(user);
            
            Session session = Session.getInstance();
            session.setID(iduser);
            session.setUsername(username);
            session.setRole(role);
            session.setContact(null);
            session.setCreated(LocalDate.now().toString());
            JOptionPane.showMessageDialog(this, "Register Berhasil!");
            
            JFrame Form = new MainJFrame();
            Form.setVisible(true);
            form.dispose();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Register Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMasukActionPerformed
    
    //Method untuk mendapatkan ID User Baru berdasarkan nomor
    public String idbaru() {
        String iduser = "";
        try(java.sql.Connection conn=(Connection)config.configDB()){
            String query = "SELECT Id_user FROM user ORDER BY Id_user DESC LIMIT 1";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                int iduserbaru = konversiid(rs.getString("Id_user")) + 1;
                iduser = String.format("U%02d", iduserbaru);
            } else {
                iduser = "U01";
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error 1", JOptionPane.ERROR_MESSAGE);
        }
        return iduser;
    }
    
    private void txtKonfirmasiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKonfirmasiPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKonfirmasiPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        form.setLoginRegister("log in");
    }//GEN-LAST:event_btnLoginActionPerformed

    //Method untuk Konversi ID menjadi Nomor
    private int konversiid(String input) {
        int result = 0;
        if (input.length() > 1) {
            String substring = input.substring(1);

            try {
                result = Integer.parseInt(substring);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Tidak dapat mengonversi ke integer", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Input terlalu pendek", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        return result;
    }
    
    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if (txtUsername.getText().equals("Username")) {
            txtUsername.setText("");
            txtUsername.setForeground(form.warnaHitam);
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if (txtUsername.getText().isEmpty()) {
            txtUsername.setForeground(form.warnaAbu);
            txtUsername.setText("Username");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (new String(txtPassword.getPassword()).equals("Password")) {
            txtPassword.setText("");
            txtPassword.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (new String(txtPassword.getPassword()).isEmpty()) {
            txtPassword.setText("Password");
            txtPassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtKonfirmasiPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKonfirmasiPasswordFocusGained
        if (new String(txtKonfirmasiPassword.getPassword()).equals("Konfirmasi Password")) {
            txtKonfirmasiPassword.setText("");
            txtKonfirmasiPassword.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_txtKonfirmasiPasswordFocusGained

    private void txtKonfirmasiPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKonfirmasiPasswordFocusLost
        if (new String(txtKonfirmasiPassword.getPassword()).isEmpty()) {
            txtKonfirmasiPassword.setText("Konfirmasi Password");
            txtKonfirmasiPassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_txtKonfirmasiPasswordFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtKonfirmasiPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
